name: Sync boilerplate
# Copier itself provide an action for making update with boilerplate
# https://copier.readthedocs.io/en/stable/updating/
# TODO: After camp update wiki and add link to it

# But we create our own action with some differences:
# - Add ssh-agent action for accessing private boilerplate
# - Use Github App to generate token for creating PR
# - Just create one PR for updating the changes with boilerplate

on:
  schedule:
  # Run action at 00:00 every Monday https://crontab.guru/#0_0_*_*_1
  - cron: '0 0 * * 1'
  # or trigger action manually
  workflow_dispatch:

jobs:
  sync_python_camp_boilerplate:
    name: Sync python camp boilerplate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up ssh-agent
        # Doc for action: https://github.com/webfactory/ssh-agent/
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.CAMP_BOILERPLATE_PRIVATE_KEY }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Sync boilerplate
        run: |
          pip install copier
          copier update --skip-answered --trust --skip-tasks
      - name: Generate token
        # Docs for action: https://github.com/marketplace/actions/github-app-token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.SARITASA_GITHUB_BOT_ID }}
          private_key: ${{ secrets.SARITASA_GITHUB_BOT_PRIVATE_KEY }}
      - name: Create Pull Request
        # Docs for action: https://github.com/marketplace/actions/create-pull-request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "[automated-commit] Sync boilerplate updates"
          title: Sync python camp boilerplate
          body: Created by GitHub Actions
          base: develop
          labels: automated-pr
          branch: feature/sync-boilerplate
          delete-branch: true
